# Generated by Django 4.1.7 on 2023-03-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('specialite', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('mat', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField()),
                ('niveau', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], max_length=20)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.domaine')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.filiere')),
            ],
        ),
    ]
