# Generated by Django 4.1.7 on 2023-03-31 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='domaine',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='base.domaine'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='base.filiere'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(blank=True, choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], max_length=20),
        ),
    ]
